repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-toml # check toml
      - id: check-ast # check python syntax tree
      - id: check-merge-conflict # check for merge conflicts

  - repo: https://github.com/ariebovenberg/slotscheck
    rev: v0.19.1
    hooks:
      - id: slotscheck # check for unused slots
        exclude: test_*|legacy|docs|migrations|scripts|
        entry: env PYTHONPATH=src slotscheck

  - repo: local
    hooks:
      - id: ruff
        name: ruff
        entry: ruff check
          --force-exclude --fix
        language: python
        types_or: [python, pyi]
        require_serial: true
        additional_dependencies: []
        files: ^(saq/|tests/|setup.py)
      - id: ruff-format
        name: ruff-format
        entry: ruff format
          --force-exclude
        language: python
        types_or: [python, pyi]
        require_serial: true
