repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-ast # check python syntax tree
      - id: check-case-conflict # check for case conflicts
      - id: check-merge-conflict # check for merge conflicts
      - id: check-toml # check toml
      - id: debug-statements # check for debug statements
      - id: mixed-line-ending # fix mixed line endings
      # - id: trailing-whitespace # trim trailing whitespace # if u whant use this, install black formatter and setup

  # - repo: https://github.com/pre-commit/mirrors-prettier
  #   rev: v4.0.0-alpha.8
  #   hooks:
  #     - id: prettier # format js code
  #       exclude: templates|migrations|scripts|docs|dist|.venv|public

  - repo: https://github.com/ariebovenberg/slotscheck
    rev: v0.19.1
    hooks:
      - id: slotscheck # check for unused slots
        exclude: test_*|legacy|docs|migrations|scripts|
        entry: env PYTHONPATH=src slotscheck

  - repo: local
    hooks:
      - id: ruff
        name: ruff
        entry: ruff check
          --force-exclude --fix
        language: python
        types_or: [python, pyi]
        require_serial: true
        additional_dependencies: []
        files: ^(saq/|tests/|setup.py)
      - id: ruff-format
        name: ruff-format
        entry: ruff format
          --force-exclude
        language: python
        types_or: [python, pyi]
        require_serial: true
      # - id: mypy
      #   name: mypy
      #   entry: mypy saq
      #   language: system
      #   types: [python]
      #   files: ^(src/app)
      #   pass_filenames: false
