from typing import Protocol, Self


class ISpecification(Protocol):
    def is_satisfied_by(self, obj: object) -> bool: ...

    def __and__(self, other: "ISpecification") -> "ISpecification": ...

    def __or__(self, other: "ISpecification") -> "ISpecification": ...

    def __invert__(self) -> "ISpecification": ...
