version: "3.9"

demoapp:
  services:
    requests:
      data: ""
      swagger:
        path: "swagger"
        file: "swagger.yaml"
        url: "/ui/"
        project_dir: "packages/demoapp"

      tracer:
        client: "jaeger"
        host: "localhost"
        component_name: "demoapp"

      metrics: true

    config:
      DEBUG: false
      TESTING: false
      APP_NAME: "demoapp"
      APPLICATION_ROOT: "/"
      SQLALCHEMY_TRACK_MODIFICATIONS: true
      SECRET_KEY: "dont_expose_me"
      DATABASE: ":memory:"
      SQLALCHEMY_DATABASE: "sqlite+aiosqlite:///:memory:"

networks:
  - gateway.net:
      driver: bridge

volumes:
  - tmp-volume:
      { driver: local, driver_opts: { o: bind, type: none, device: /tmp } }

configs:
  - nginx-balancer-conf:
      file: "./tooling/nginx/balancer-nginx.conf"
      target: "/etc/nginx/nginx.conf"
  - draft-app-conf:
    content: |
      LITESTAR_DEBUG=True \
      LITESTAR_SERVER_HOST=0.0.0.0 \
      LITESTAR_SERVER_PORT=8000
