services:
  requests:
    data: ""
    swagger:
      path: "swagger"
      file: "swagger.yaml"
      url: "/schema/"
      project_dir: "services/messenger"

    tracer:
      client: "jaeger"
      host: "localhost"
      component_name: "demoapp"

    metrics: true

  configs:
    DEBUG: false
    LITESTAR_DEBUG: true
    SECRET_KEY: "_dont_expose_me_"
    SQLALCHEMY_DATABASE: "sqlite+aiosqlite:///tmp-volume/database.db"

networks:
  - gateway.net:
      driver: bridge

volumes:
  - tmp-volume:
      { driver: local, driver_opts: { o: bind, type: none, device: tmp } }

configs:
  - nginx-balancer-conf:
      file: "./tooling/nginx/balancer-nginx.conf"
      target: "/etc/nginx/nginx.conf"
  - draft-app-conf:
    content: |
      LITESTAR_DEBUG=True \
      LITESTAR_SERVER_HOST=0.0.0.0 \
      LITESTAR_SERVER_PORT=8000
